# Generated by Django 2.1.1 on 2018-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180916_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_ims',
            name='user',
        ),
        migrations.AddField(
            model_name='history_ims',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
