# Generated by Django 2.1.1 on 2018-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180916_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_ims',
            name='ads_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='apfs_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='ees_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='efs_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='gs_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='has_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='hers_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='hirs_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='kes_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='kfs_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='sers_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
        migrations.AddField(
            model_name='history_ims',
            name='sirs_eval',
            field=models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32),
        ),
    ]
