# Generated by Django 2.1.1 on 2018-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180926_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_fp',
            name='csrt',
            field=models.FloatField(default=0),
        ),
    ]
