# Generated by Django 2.1.1 on 2018-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180919_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_JF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('kf', models.IntegerField(default=0)),
                ('ke', models.IntegerField(default=0)),
                ('apf', models.IntegerField(default=0)),
                ('ad', models.IntegerField(default=0)),
                ('hf', models.IntegerField(default=0)),
                ('her', models.IntegerField(default=0)),
                ('hir', models.IntegerField(default=0)),
                ('ef', models.IntegerField(default=0)),
                ('ee', models.IntegerField(default=0)),
                ('ser', models.IntegerField(default=0)),
                ('sir', models.IntegerField(default=0)),
                ('kf_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('ke_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('apf_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('ad_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('hf_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('her_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('hir_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('ef_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('ee_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('ser_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('sir_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=32)),
                ('kf_mean', models.IntegerField(default=0)),
                ('ke_mean', models.IntegerField(default=0)),
                ('apf_mean', models.IntegerField(default=0)),
                ('ad_mean', models.IntegerField(default=0)),
                ('hf_mean', models.IntegerField(default=0)),
                ('her_mean', models.IntegerField(default=0)),
                ('hir_mean', models.IntegerField(default=0)),
                ('ef_mean', models.IntegerField(default=0)),
                ('ee_mean', models.IntegerField(default=0)),
                ('ser_mean', models.IntegerField(default=0)),
                ('sir_mean', models.IntegerField(default=0)),
                ('kf_sd', models.IntegerField(default=0)),
                ('ke_sd', models.IntegerField(default=0)),
                ('apf_sd', models.IntegerField(default=0)),
                ('ad_sd', models.IntegerField(default=0)),
                ('hf_sd', models.IntegerField(default=0)),
                ('her_sd', models.IntegerField(default=0)),
                ('hir_sd', models.IntegerField(default=0)),
                ('ef_sd', models.IntegerField(default=0)),
                ('ee_sd', models.IntegerField(default=0)),
                ('ser_sd', models.IntegerField(default=0)),
                ('sir_sd', models.IntegerField(default=0)),
            ],
        ),
    ]
