# Generated by Django 2.1.1 on 2018-10-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20181011_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp',
            name='csrt_mean',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fp',
            name='csrt_sd',
            field=models.FloatField(default=0),
        ),
    ]
