# Generated by Django 2.1.1 on 2018-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_history_jf_jf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=32)),
                ('fdt_mean', models.IntegerField(default=0)),
                ('hpt9_mean', models.IntegerField(default=0)),
                ('seb_mean', models.IntegerField(default=0)),
                ('lj_mean', models.IntegerField(default=0)),
                ('mwt6_mean', models.IntegerField(default=0)),
                ('vj_mean', models.IntegerField(default=0)),
                ('tst_mean', models.IntegerField(default=0)),
                ('csrt_mean', models.IntegerField(default=0)),
                ('sts_mean', models.IntegerField(default=0)),
                ('botb_mean', models.IntegerField(default=0)),
                ('fdt_sd', models.IntegerField(default=0)),
                ('hpt9_sd', models.IntegerField(default=0)),
                ('seb_sd', models.IntegerField(default=0)),
                ('lj_sd', models.IntegerField(default=0)),
                ('mwt6_sd', models.IntegerField(default=0)),
                ('vj_sd', models.IntegerField(default=0)),
                ('tst_sd', models.IntegerField(default=0)),
                ('csrt_sd', models.IntegerField(default=0)),
                ('sts_sd', models.IntegerField(default=0)),
                ('botb_sd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History_FP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('fdt', models.IntegerField(default=0)),
                ('hpt9', models.IntegerField(default=0)),
                ('seb', models.IntegerField(default=0)),
                ('lj', models.IntegerField(default=0)),
                ('mwt6', models.IntegerField(default=0)),
                ('vj', models.IntegerField(default=0)),
                ('tst', models.IntegerField(default=0)),
                ('csrt', models.IntegerField(default=0)),
                ('sts', models.IntegerField(default=0)),
                ('botb', models.IntegerField(default=0)),
                ('fdt_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('hpt9_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('seb_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('lj_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('mwt6_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('vj_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('tst_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('csrt_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('sts_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('botb_eval', models.CharField(choices=[('Weak', 'Weak'), ('Normal', 'Normal'), ('Strong', 'Strong')], default='Weak', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
